apiVersion: apps/v1
kind: Deployment
metadata:
  name: distributed-ai-master
  namespace: distributed-ai
spec:
  replicas: 1
  selector:
    matchLabels:
      app: distributed-ai
      component: master
  template:
    metadata:
      labels:
        app: distributed-ai
        component: master
    spec:
      serviceAccountName: distributed-ai-sa
      containers:
        - name: master
          image: hoffeloffe/distributed-ai-cluster:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: NODE_ROLE
              value: "master"
            - name: MASTER_NODE_ID
              value: "master-1"
            - name: LOG_LEVEL
              value: "INFO"
            - name: K8S_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: MODEL_STORAGE_PATH
              value: "/models"
            - name: PROMETHEUS_PORT
              value: "9090"
          ports:
            - containerPort: 8080
              name: api
          resources:
            requests:
              cpu: "500m"
              memory: "1Gi"
            limits:
              cpu: "1000m"
              memory: "2Gi"
          volumeMounts:
            - name: model-storage
              mountPath: /models
      volumes:
        - name: model-storage
          persistentVolumeClaim:
            claimName: distributed-ai-models
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: distributed-ai-worker
  namespace: distributed-ai
spec:
  replicas: 3
  selector:
    matchLabels:
      app: distributed-ai
      component: worker
  template:
    metadata:
      labels:
        app: distributed-ai
        component: worker
    spec:
      serviceAccountName: distributed-ai-sa
      containers:
        - name: worker
          image: hoffeloffe/distributed-ai-cluster:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: NODE_ROLE
              value: "worker"
            - name: MASTER_SERVICE_NAME
              value: "distributed-ai-master"
            - name: K8S_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: LOG_LEVEL
              value: "INFO"
            - name: MODEL_STORAGE_PATH
              value: "/models"
            - name: PROMETHEUS_PORT
              value: "9090"
          ports:
            - containerPort: 8080
              name: inference
          resources:
            requests:
              cpu: "1000m"
              memory: "2Gi"
            limits:
              cpu: "2000m"
              memory: "4Gi"
          volumeMounts:
            - name: model-storage
              mountPath: /models
      volumes:
        - name: model-storage
          persistentVolumeClaim:
            claimName: distributed-ai-models
