apiVersion: v1
kind: Service
metadata:
  name: distributed-ai-master
  namespace: distributed-ai
  labels:
    app: distributed-ai
    component: master
spec:
  type: ClusterIP
  selector:
    app: distributed-ai
    component: master
  ports:
    - name: api
      port: 8080
      targetPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: distributed-ai-worker
  namespace: distributed-ai
  labels:
    app: distributed-ai
    component: worker
spec:
  type: ClusterIP
  selector:
    app: distributed-ai
    component: worker
  ports:
    - name: inference
      port: 8080
      targetPort: 8080
